[package]
name = "rskafka-wire-format"
version = "0.1.0"
authors = ["Jacek Chmiel <jacek@chmiel.cc>"]
edition = "2018"

[dependencies]
nom = "5.1.1"
uuid = "0.8.1"
byteorder = "1.3.4"
thiserror = "1.0.16"
integer-encoding = "1.1.5"