[package]
name = "rskafka-proto"
version = "0.1.0"
authors = ["Jacek Chmiel <jacek@chmiel.cc>"]
edition = "2018"

[dependencies]
log = "0.4.8"
nom = "5.1.1"
uuid = "0.8.1"
byteorder = "1.3.4"
either = "1.5.3"
thiserror = "1.0.16"

[dev-dependencies]
env_logger = "0.7.1"